name: SeaCreaturesPlugin
version: '${version}'
main: org.rolypolyvole.seacreatures.SeaCreaturesPlugin
api-version: '1.20'
description: A Minecraft java plugin that enhances your fishing experience! Adds multiple custom sea creatures, all with special custom abilities and AI.
